name: Deployment pipeline

on:
  push:
    branches:
      - main

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./my-fullstack-app 

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install dependencies        
        run: npm install:all
        
      - name: Check style
        run: npm run lint
#just to trigger this eslint test
      - name: Build
        run: npm run build
      
      - name: Run test
        run: npm run test
